export const GET_CONFIG_BY_ID = 'GET_CONFIG_BY_ID'
export const GET_CONFIG_BY_ID_SUCCESS = 'GET_CONFIG_BY_ID_SUCCESS'

export const GET_USER_BY_RFID = 'GET_USER_BY_RFID'
export const GET_USER_BY_RFID_SUCCESS = 'GET_USER_BY_RFID_SUCCESS'
export const GET_USER_BY_RFID_ERROR = 'GET_USER_BY_RFID_ERROR'
export const CREATE_ITEM = 'CREATE_ITEM'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const PRINT_LABEL = 'PRINT_LABEL'
export const PRINT_LABEL_SUCCESS = 'PRINT_LABEL_SUCCESS'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
